INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (103, 'Skopje', 'MAC', 'Macédonien, albanais', 'Macédoine', 2.009, 'Europe', 25713.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (44, 'Luanda', 'ANG', 'Portugais', 'Angola', 12.5, 'Afrique', 1246700.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (136, 'Caracas', 'VEN', 'Espagnol', 'Venezuela', 3.27, 'Amérique du Sud', 174810.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (102, 'Luxembourg', 'LUX', 'Luxembourgeois', 'Luxembourg', 0.455, 'Europe', 2586.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (131, 'Tunis', 'TUN', 'Arabe,français', 'Tunisie', 8.987, 'Afrique', 163310.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (73, 'Yamoussoukro', 'COT', 'Français', 'Côte d''Ivoire', 15.3, 'Afrique', 322463.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (120, 'Al-Dawha (Doha)', 'QAT', 'Arabe, anglais', 'Qatar', 0.642, 'Asie', 11437.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (74, 'Zagreb', 'CRO', 'Croate, serbe, slovène', 'Croatie', 4.78, 'Europe', 56538.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (130, 'Bangkok', 'THA', 'Thaïlandais', 'Thaïlande', 58.9, 'Asie', 513120.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (83, 'Washington', 'USA', 'Anglais', 'Etats-Unis', 284.5, 'Amérique du Nord', 9372610.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (69, 'Nicosie', 'CHY', 'Grec, turque', 'Chypre', 0.753, 'Asie', 9251.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (94, 'Rome', 'ITA', 'Italien', 'Italie', 57.789, 'Europe', 301320.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (53, 'Bruxelles', 'BEL', 'Néerlandais, français, allemand', 'Belgique', 10.174, 'Europe', 30513.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (55, 'Hamilton', 'BER', 'Anglais', 'Bermudes', 0.062, 'Amérique du Nord', 53.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (105, 'Male', 'MAL', 'Divehi', 'Maldives', 0.253, 'Asie', 300.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (111, 'Yaren', 'NAU', 'Anglais, nauruan', 'Nauru', 0.011, 'Océanie', 21.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (108, 'Mexico', 'MEX', 'Espagnol', 'Mexique', 999.6, 'Amérique du Nord', 1958200.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (70, 'Santa Fé de Bogotà', 'COL', 'Espagnol', 'Colombie', 38.6, 'Amérique du Sud', 1138910.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (81, 'Madrid', 'ESP', 'Espagnol', 'Espagne', 39.8, 'Europe', 504750.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (49, 'Bakou', 'AZE', 'Azeri', 'Azerbaïdjan', 7.8, 'Asie', 86600.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (117, 'Lima', 'PER', 'Espagnol', 'Pérou', 23.818, 'Amérique du Sud', 1285220.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (93, 'Jérusalem', 'ISR', 'Hébreu', 'Israël', 6.2, 'Asie', 20700.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (40, 'Tirana', 'ALB', 'Albanais', 'Albanie', 3.43, 'Europe', 28750.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (90, 'New Delhi', 'IND', 'Hindi, anglais', 'Inde', 1007.0, 'Asie', 3287590.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (48, 'Vienne', 'AUT', 'Allemand', 'Autriche', 8.1, 'Europe', 83850.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (118, 'Varsovie', 'POL', 'Polonais', 'Pologne', 38.7, 'Europe', 312683.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (110, 'Monaco', 'MON', 'Français, italien', 'Monaco', 0.032, 'Europe', 1.9);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (127, 'Stockholm', 'SUE', 'Suédois', 'Suède', 8.896, 'Europe', 449964.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (62, 'Ouagadougou', 'BUR', 'Français, moré', 'Burkina Faso', 12.04, 'Afrique', 274200.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (126, 'Ljubljana', 'SLV', 'Slovène, serbo-croate', 'Slovénie', 2.0, 'Europe', 20256.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (137, 'Harare', 'ZIM', 'Anglais, afrikaans, allemand', 'Zimbabwe', 11.011, 'Afrique', 390580.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (64, 'Phom Penh', 'CAM', 'Khmer', 'Cambodge', 10.024, 'Asie', 181040.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (113, 'Oslo', 'NOR', 'Norvégien', 'Norvège', 4.519, 'Europe', 324219.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (59, 'Gaborone', 'BOT', 'Anglais, bantou', 'Botswana', 1.53, 'Afrique', 781730.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (78, 'Saint Domingue', 'DOM', 'Espagnol', 'Rép. Dominicaine', 7.822, 'Antilles', 48730.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (72, 'San José', 'COS', 'Espagnol', 'Costa Rica', 3.399, 'Amérique Centrale', 51100.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (52, 'Bridgetown', 'BAR', 'Anglais', 'Barbade', 0.27, 'Antilles', 430.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (61, 'Sofia', 'BUL', 'Bulgare, turc', 'Bulgarie', 8.24, 'Europe', 110912.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (106, 'Rabat', 'MAR', 'Arabe, français', 'Maroc', 28.89, 'Afrique', 698670.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (65, 'Ottawa', 'CAN', 'Anglais, français', 'Canada', 30.75, 'Amérique du Nord', 9976140.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (76, 'Copenhague', 'DAN', 'Danois', 'Danemark', 5.398, 'Europe', 43070.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (91, 'Dublin', 'IRL', 'Anglais, gaélique', 'Irlande', 3.789, 'Europe', 70282.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (89, 'Budapest', 'HON', 'Hongrois', 'Hongrie', 10.208, 'Europe', 93030.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (45, 'Buenos Aires', 'ARG', 'Espagnol', 'Argentine', 36.6, 'Amérique', 2737000.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (95, 'Kingston', 'JAM', 'Anglais', 'Jamaïque', 2.522, 'Amérique Centrale', 10990.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (104, 'Antananarivo', 'MAD', 'Malgache, français', 'Madagascar', 15.24, 'Afrique', 587040.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (112, 'Katmandou', 'NEP', 'Népali', 'Népal', 22.6, 'Asie', 140800.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (109, 'Chisinau', 'MOL', 'Moldave, ukrainien, russe', 'Moldavie', 4.357, 'Europe', 33700.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (88, 'Guatemala', 'GUA', 'Espagnol', 'Guatemala', 12.22, 'Amérique Centrale', 108890.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (124, 'Singapour', 'SIN', 'Malais, chinois, tamoul, anglais', 'Singapour', 5.38, 'Asie', 647.8);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (97, 'Amman', 'JOR', 'Arabe', 'Jordanie', 6.3, 'Asie', 89210.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (114, 'Wellington', 'NZE', 'Anglais', 'Nouvelle Zélande', 3.601, 'Océanie', 268680.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (84, 'Stanley', 'FAL', 'Anglais', 'Iles Falkland', 0.0025, 'Amérique du Sud', 12173.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (122, 'Londres', 'ROY', 'Anglais, gaélique, écossais', 'Royaume-Uni', 59.5, 'Europe', 244119.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (51, 'Dacca', 'BAN', 'Bengali', 'Bangladesh', 126.5, 'Asie', 143998.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (98, 'Riga', 'LET', 'Letton, russe', 'Lettonie', 2.385, 'Europe', 64589.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (134, 'Montevideo', 'URU', 'Espagnol', 'Uruguay', 3.27, 'Amérique du Sud', 174810.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (132, 'Ankara', 'TUR', 'Turc', 'Turquie', 65.5, 'Asie', 779450.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (80, 'Quito', 'EQU', 'Espagnol', 'Equateur', 12.5, 'Amérique du Sud', 283560.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (41, 'Alger', 'ALG', 'Arabe, français', 'Algérie', 30.2, 'Afrique', 2381740.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (87, 'Athènes', 'GRE', 'Grec', 'Grèce', 10.862, 'Europe', 131944.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (119, 'Lisbonne', 'POR', 'Portugais', 'Portugal', 10.102, 'Europe', 92082.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (79, 'Le Caire', 'EGY', 'Arabe, anglais', 'Egypte', 62.8, 'Afrique', 1001450.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (50, 'Nassau', 'BAH', 'Anglais, créole ang.', 'Bahama', 0.302, 'Amérique', 10000.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (39, 'Pretoria', 'AFR', 'Afrikaans, anglais', 'Afrique du Sud', 43.4, 'Afrique', 1221040.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (63, 'George Town', 'CAI', 'Anglais', 'Caïmans', 0.037716, 'Antilles', 263.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (128, 'Berne', 'SUI', 'Allemand, français, italien, romanche', 'Suisse', 7.26, 'Europe', 41290.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (85, 'Helsinki', 'FIN', 'Finnois, suédois', 'Finlande', 5.223, 'Europe', 338142.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (68, 'Taipei', 'TAI', 'Chinois, taïwanais', 'Taïwan', 21.5, 'Asie', 36179.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (133, 'Kiev', 'UKR', 'Ukrainien, russe', 'Ukraine', 49.55, 'Europe', 603700.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (100, 'Vaduz', 'LIE', 'Allemand', 'Liechtenstein', 0.031, 'Europe', 160.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (43, 'Andorre-la-Vieille', 'AND', 'Catalan, espagnol, français', 'Andorre', 0.0652, 'Europe', 466.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (129, 'Prague', 'TCH', 'Tchèque, slovaque, hongrois', 'République Tchèque', 10.286, 'Europe', 78838.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (66, 'Santiago', 'CHL', 'Espagnol', 'Chili', 15.25, 'Amérique du Sud', 756950.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (82, 'Tallinn', 'EST', 'Estonien, russe', 'Estonie', 1.421, 'Europe', 45100.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (67, 'Pékin', 'CHI', 'Chinois mandarin', 'Chine', 1265.25, 'Asie', 9571300.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (121, 'Bucarest', 'ROU', 'Roumain, hongrois', 'Roumanie', 22.5, 'Europe', 237499.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (86, 'Paris', 'FRA', 'Français', 'France', 58.804, 'Europe', 551500.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (58, 'La Paz', 'BOL', 'Espagnol, quéchua', 'Bolivie', 8.2, 'Amérique du Sud', 1098580.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (56, 'Thimbu', 'BHO', 'Dzong-ka', 'Bhoutan', 0.695, 'Asie', 47000.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (99, 'Beyrouth', 'LIB', 'Arabe', 'Liban', 4.005, 'Asie', 10400.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (57, 'Minsk', 'BIE', 'Biélorusse, russe', 'Biélorussie', 10.409, 'Europe', 207600.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (116, 'Amsterdam', 'HOL', 'Néerlandais', 'Pays-Bas', 16.131, 'Europe', 37330.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (75, 'La Havane', 'CUB', 'Espagnol', 'Cuba', 11.2, 'Amérique du Sud', 110860.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (125, 'Bratislava', 'SLO', 'Slovaque', 'Slovaquie', 5.38, 'Europe', 49035.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (123, 'Moscou', 'RUS', 'Russe', 'Russie', 59.5, 'Europe', 1.00754E7);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (42, 'Berlin', 'ALL', 'Allemand', 'Allemagne', 82.079, 'Europe', 356910.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (46, 'Erevan', 'ARM', 'Arménien', 'Arménie', 3.76, 'Asie', 29000.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (107, 'Port-Louis', 'MAU', 'Créole, français', 'Maurice', 1.128, 'Océan Indien', 1865.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (47, 'Canberra', 'AUS', 'Anglais', 'Australie', 18.75, 'Océanie', 7686850.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (60, 'Brasilia', 'BRE', 'Portugais', 'Brésil', 160.52, 'Amérique du Sud', 8511970.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (135, 'Port-Vila', 'VAN', 'Bichlamar, anglais, français', 'Vanuatu', 0.169, 'Océanie', 12190.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (115, 'Port-Moresby', 'PAP', 'Néo-mélanésien', 'Papouasie-Nouvelle-Guinée', 4.6, 'Océanie', 462840.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (54, 'Porto Novo', 'BEN', 'Français', 'Bénin', 6.2, 'Afrique', 112620.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (77, 'Djibouti', 'DJI', 'Arabe, français', 'Djibouti', 0.685, 'Afrique', 23200.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (101, 'Vilnius', 'LIT', 'Lituanien, russe, polonais', 'Lituanie', 3.7, 'Europe', 65200.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (96, 'Tokyo', 'JAP', 'Japonais', 'Japon', 126.5, 'Asie', 377800.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (71, 'Séoul', 'COR', 'Coréen', 'Corée du Sud', 47.1, 'Asie', 99020.0);
INSERT INTO PAYS (ID, CAPITALE, CODE, LANGUE, NOM, POPULATION, REGION, SUPERFICIE) 
	VALUES (92, 'Reykjavik', 'ISL', 'Islandais', 'Islande', 0.291, 'Europe', 102845.0);
