CREATE TABLE PAYS (ID BIGINT NOT NULL, CAPITALE VARCHAR(255), CODE VARCHAR(255), LANGUE VARCHAR(255), NOM VARCHAR(255), POPULATION DOUBLE, REGION VARCHAR(255), SUPERFICIE DOUBLE, PRIMARY KEY (ID));

CREATE TABLE CONSEILLER (ID BIGINT NOT NULL, EMAIL VARCHAR(255), NOM VARCHAR(255), PRENOM VARCHAR(255), PRIMARY KEY (ID));

CREATE TABLE VOYAGE (ID BIGINT NOT NULL, DTYPE VARCHAR(31), CODE VARCHAR(255), DESCRIPTION VARCHAR(255), DUREE INTEGER, NOM VARCHAR(255), KILOMETRAGE INTEGER, TRANSPORT VARCHAR(255), RESIDENCE VARCHAR(255), PRIMARY KEY (ID));

CREATE TABLE VOYAGE_PAYS (VOYAGE_ID BIGINT NOT NULL, PAYS_ID BIGINT NOT NULL, PRIMARY KEY (VOYAGE_ID, PAYS_ID));

CREATE TABLE DEPART (ID BIGINT NOT NULL, JOUR DATE, PRIX DOUBLE, TRANSPORT VARCHAR(255), VILLE VARCHAR(255), VOYAGE_ID BIGINT, PRIMARY KEY (ID));


-- update DEPART set jour = cast ( {fn TIMESTAMPADD(SQL_TSI_MONTH, 13, JOUR)} as DATE);


