INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (164, 65);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (170, 71);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (173, 74);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (182, 83);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (187, 88);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (174, 75);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (215, 116);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (185, 86);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (224, 125);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (143, 44);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (167, 68);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (142, 43);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (193, 94);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (153, 54);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (213, 114);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (160, 61);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (166, 67);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (198, 99);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (179, 80);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (212, 113);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (199, 100);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (159, 60);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (194, 95);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (222, 123);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (234, 135);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (172, 73);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (151, 52);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (162, 63);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (146, 47);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (156, 57);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (204, 105);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (197, 98);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (231, 132);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (229, 130);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (209, 110);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (226, 127);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (233, 134);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (195, 96);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (216, 117);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (144, 45);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (171, 72);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (177, 78);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (186, 87);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (183, 84);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (161, 62);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (235, 136);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (202, 103);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (157, 58);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (200, 101);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (148, 49);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (218, 119);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (188, 89);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (147, 48);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (192, 93);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (155, 56);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (152, 53);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (168, 69);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (207, 108);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (149, 50);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (219, 120);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (227, 128);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (176, 77);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (138, 39);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (211, 112);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (210, 111);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (163, 64);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (220, 121);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (208, 109);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (169, 70);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (230, 131);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (140, 41);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (150, 51);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (228, 129);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (184, 85);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (205, 106);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (214, 115);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (165, 66);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (139, 40);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (196, 97);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (191, 92);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (221, 122);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (181, 82);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (189, 90);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (141, 42);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (203, 104);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (201, 102);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (158, 59);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (145, 46);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (178, 79);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (223, 124);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (190, 91);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (217, 118);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (175, 76);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (180, 81);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (236, 137);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (154, 55);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (225, 126);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (206, 107);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (232, 133);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (389, 115);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (307, 74);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (354, 97);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (342, 91);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (318, 79);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (294, 67);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (268, 54);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (237, 39);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (263, 52);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (285, 63);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (434, 137);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (433, 137);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (257, 49);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (319, 80);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (348, 94);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (305, 73);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (317, 79);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (347, 94);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (280, 60);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (328, 84);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (403, 122);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (337, 89);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (391, 116);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (374, 107);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (335, 88);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (315, 78);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (346, 93);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (357, 99);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (378, 109);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (398, 119);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (276, 58);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (397, 119);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (292, 66);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (241, 41);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (269, 55);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (392, 116);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (262, 51);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (419, 130);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (325, 83);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (259, 50);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (275, 58);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (254, 47);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (256, 48);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (402, 121);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (341, 91);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (289, 65);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (376, 108);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (350, 95);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (295, 68);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (406, 123);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (386, 113);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (418, 129);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (339, 90);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (251, 46);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (414, 127);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (404, 122);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (373, 107);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (425, 133);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (250, 45);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (283, 62);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (306, 73);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (370, 105);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (383, 112);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (366, 103);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (351, 96);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (358, 99);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (284, 62);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (323, 82);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (261, 51);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (400, 120);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (379, 110);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (431, 136);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (408, 124);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (380, 110);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (363, 102);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (399, 120);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (322, 81);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (238, 39);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (274, 57);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (290, 65);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (381, 111);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (344, 92);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (340, 90);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (427, 134);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (411, 126);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (266, 53);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (329, 85);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (364, 102);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (369, 105);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (394, 117);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (417, 129);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (277, 59);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (264, 52);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (409, 125);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (270, 55);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (303, 72);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (267, 54);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (314, 77);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (300, 70);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (282, 61);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (310, 75);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (312, 76);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (365, 103);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (287, 64);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (296, 68);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (410, 125);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (308, 74);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (243, 42);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (385, 113);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (258, 49);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (245, 43);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (345, 93);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (286, 63);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (330, 85);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (247, 44);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (356, 98);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (367, 104);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (301, 71);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (281, 61);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (416, 128);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (246, 43);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (239, 40);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (405, 123);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (430, 135);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (428, 134);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (313, 77);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (260, 50);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (299, 70);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (321, 81);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (316, 78);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (384, 112);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (252, 46);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (407, 124);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (371, 106);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (249, 45);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (382, 111);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (412, 126);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (293, 67);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (327, 84);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (396, 118);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (390, 115);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (242, 41);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (336, 88);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (360, 100);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (415, 128);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (255, 48);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (359, 100);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (333, 87);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (377, 109);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (352, 96);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (273, 57);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (338, 89);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (349, 95);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (309, 75);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (420, 130);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (422, 131);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (332, 86);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (424, 132);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (278, 59);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (272, 56);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (279, 60);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (361, 101);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (432, 136);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (334, 87);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (413, 127);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (240, 40);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (320, 80);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (353, 97);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (395, 118);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (326, 83);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (248, 44);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (423, 132);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (311, 76);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (387, 114);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (429, 135);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (291, 66);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (355, 98);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (253, 47);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (401, 121);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (271, 56);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (331, 86);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (297, 69);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (393, 117);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (388, 114);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (372, 106);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (265, 53);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (362, 101);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (343, 92);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (244, 42);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (368, 104);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (421, 131);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (375, 108);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (426, 133);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (304, 72);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (288, 64);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (298, 69);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (302, 71);
INSERT INTO VOYAGE_PAYS (VOYAGES_ID, PAYS_ID) 
	VALUES (324, 82);
